import { pathToFileURL } from 'node:url';
import { Steng, type StengBackend, type StengOptions } from '../index.js';

/** True when this module is being executed directly instead of imported. */
function isMainModule(): boolean {
  return (
    Boolean(process.argv[1]) &&
    import.meta.url === pathToFileURL(process.argv[1]).href
  );
}

/**
 * Resolve the playground backend from CLI args or `STENG_BACKEND`.
 *
 * Supported values are `memory`, `sqlite`, and `postgres`.
 */
function parseBackend(argv: string[]): StengBackend {
  const flagIndex = argv.findIndex((arg) => arg === '--backend');
  if (flagIndex >= 0 && argv[flagIndex + 1]) {
    return normalizeBackend(argv[flagIndex + 1]);
  }

  const inline = argv.find((arg) => arg.startsWith('--backend='));
  if (inline) {
    return normalizeBackend(inline.split('=')[1]);
  }

  const envBackend = process.env.STENG_BACKEND;
  if (envBackend) {
    return normalizeBackend(envBackend);
  }

  return 'memory';
}

/** Validate a raw backend string and convert it to the typed backend union. */
function normalizeBackend(value: string): StengBackend {
  if (value === 'memory' || value === 'sqlite' || value === 'postgres') {
    return value;
  }
  throw new Error(
    `Unsupported backend "${value}". Use memory, sqlite, or postgres.`,
  );
}

/** Read the cluster short code used in autogenerated ids for this playground run. */
function resolveClusterShort(): string {
  return process.env.STENG_CLUSTER_SHORT?.trim() || 'demo';
}

function readFlag(argv: string[], name: string): string | undefined {
  const flagIndex = argv.findIndex((arg) => arg === name);
  if (flagIndex >= 0 && argv[flagIndex + 1]) {
    return argv[flagIndex + 1];
  }
  const inline = argv.find((arg) => arg.startsWith(`${name}=`));
  return inline ? inline.slice(name.length + 1) : undefined;
}

function resolveStengOptions(
  backend: StengBackend,
  argv: string[] = process.argv.slice(2),
): StengOptions {
  const clusterShort = resolveClusterShort();
  if (backend === 'sqlite') {
    return {
      backend,
      clusterShort,
      sqlite: {
        filename:
          readFlag(argv, '--sqlite-file') ??
          process.env.STENG_SQLITE_FILE ??
          undefined,
      },
    };
  }
  if (backend === 'postgres') {
    const connectionString =
      readFlag(argv, '--pg-url') ?? process.env.STENG_POSTGRES_URL;
    if (!connectionString) {
      throw new Error(
        'Postgres playground requires a real server. Set STENG_POSTGRES_URL or pass --pg-url postgres://...',
      );
    }
    return {
      backend,
      clusterShort,
      postgres: {
        connectionString,
        schema:
          readFlag(argv, '--pg-schema') ??
          process.env.STENG_POSTGRES_SCHEMA ??
          'steng_playground',
      },
    };
  }
  return {
    backend,
    clusterShort,
  };
}

/**
 * Run one end-to-end CRUD demo against the selected backend.
 *
 * @param backend Which storage backend to use. The rest of the code stays the same.
 */
export async function runBasicCrudPlayground(
  backend: StengBackend = 'memory',
): Promise<void> {
  const options = resolveStengOptions(backend);
  const clusterShort = options.clusterShort ?? 'demo';
  const steng = new Steng(options);

  try {
    const table = await steng.ensure_table('pos', 'miami1', 'orders', 'json');
    await steng.add_index(table.tableId, 'createdAt', 'time');
    await steng.add_index(table.tableId, 'status', 'str');
    await steng.add_index(table.tableId, 'equipmentId', 'str');
    await steng.add_index(table.tableId, 'orderRef', 'str');
    await steng.add_index(table.tableId, 'tags', 'str', true);
    await steng.set_table_config(table.tableId, {
      timeField: 'createdAt',
      idPrefix: 'orders',
    });

    const now = Date.now();
    const first = await steng.add_obj(table.tableId, {
      createdAt: now,
      status: 'PENDING',
      equipmentId: 'eq_1',
      customerName: 'Ava',
      tags: ['lunch', 'takeout'],
      totalCents: 1250,
    });
    const batch = await steng.add_objs(table.tableId, [
      {
        value: {
          orderRef: 'manual_demo',
          createdAt: now + 1,
          status: 'READY',
          equipmentId: 'eq_2',
          customerName: 'Ben',
          tags: ['pickup'],
          totalCents: 800,
        },
      },
      {
        value: {
          createdAt: now + 2,
          status: 'PENDING',
          equipmentId: 'eq_1',
          customerName: 'Cara',
          tags: ['lunch', 'vip'],
          totalCents: 1950,
        },
      },
    ]);
    const inserted = { ids: [first.id, ...batch.ids] };

    const byId = await steng.get_objs(table.tableId, inserted.ids, null, 0, 10);
    const page1 = await steng.get_objs(table.tableId, null, null, 0, 2);
    const page2 = await steng.get_objs(
      table.tableId,
      null,
      null,
      page1.next_pos,
      2,
    );

    await steng.update_objs(table.tableId, [
      {
        id: inserted.ids[0],
        patch: {
          status: 'COOKING',
          notes: 'No onions',
        },
        merge: 'shallow',
      },
    ]);

    await steng.replace_objs(table.tableId, [
      {
        id: inserted.ids[1],
        value: {
          orderRef: 'manual_demo',
          createdAt: now + 2,
          status: 'READY',
          equipmentId: 'eq_2',
          totalCents: 900,
          customerNote: 'Pickup window 5m',
        },
      },
    ]);

    const updatedRow = await steng.get_objs(
      table.tableId,
      [inserted.ids[0]],
      null,
      0,
      1,
    );
    const indexes = await steng.list_indexes(table.tableId);
    const cookingOnEq1 = await steng.get_objs(
      table.tableId,
      null,
      [
        ['status', '==', 'COOKING'],
        ['equipmentId', '==', 'eq_1'],
      ],
      0,
      10,
    );
    const readyOrCooking = await steng.get_objs(
      table.tableId,
      null,
      [['status', 'in', ['READY', 'COOKING']]],
      0,
      10,
    );
    const lunchOrders = await steng.get_objs(
      table.tableId,
      null,
      [['tags', 'contains', 'lunch']],
      0,
      10,
    );
    const generatedIdPrefix = await steng.get_objs(
      table.tableId,
      null,
      [['id', 'prefix', `orders_${clusterShort}_`]],
      0,
      10,
    );

    const replacedRow = await steng.get_objs(
      table.tableId,
      [inserted.ids[1]],
      null,
      0,
      1,
    );

    await steng.delete_objs(table.tableId, [inserted.ids[2]]);
    const afterDelete = await steng.get_objs(
      table.tableId,
      inserted.ids,
      null,
      0,
      10,
    );
    const ops = await steng.read_ops_since(table.tableId, 0, 20);
    const listedTables = await steng.list_tables('pos', 'miami1');

    console.log(
      JSON.stringify(
        {
          backend,
          clusterShort,
          tableInfo: await steng.get_table_info_by_id(table.tableId),
          indexes,
          listedTables,
          inserted: {
            ids: inserted.ids,
            appLevelIds: ['manual_demo'],
          },
          fetchedById: byId.items,
          pagedReads: {
            page1: page1.items,
            page2: page2.items,
          },
          filteredQueries: {
            cookingOnEq1: cookingOnEq1.items,
            readyOrCooking: readyOrCooking.items,
            lunchOrders: lunchOrders.items,
            generatedIdPrefix: generatedIdPrefix.items,
          },
          updatedRow: updatedRow.items,
          replacedRow: replacedRow.items,
          afterDelete: afterDelete.items,
          oplog: ops,
        },
        null,
        2,
      ),
    );
  } finally {
    await steng.close();
  }
}

if (isMainModule()) {
  runBasicCrudPlayground(parseBackend(process.argv.slice(2))).catch((error) => {
    console.error(error);
    process.exitCode = 1;
  });
}
