/** Supported table storage modes. */
export type TableType = 'json' | 'binary';

/** Secondary index types supported by `steng` filters. */
export type IndexType = 'i64' | 'str' | 'bool' | 'time' | 'hash64';

/** Comparison operators accepted by `get_objs` filters. */
export type FilterOp =
  | '=='
  | '!='
  | '>'
  | '>='
  | '<'
  | '<='
  | 'between'
  | 'in'
  | 'contains'
  | 'prefix';

/**
 * One filter condition in `[field, operator, value]` form.
 *
 * Example: `["status", "==", "READY"]`
 */
export type FilterClause = [field: string, op: FilterOp, value: unknown];

/** A list of AND-ed filter clauses, or `null` for no filtering. */
export type Filter = FilterClause[] | null;

/** One index definition stored in table config. */
export type IndexConfig = {
  /** Underlying index value type. */
  type: IndexType;
  /** Whether the indexed field can emit multiple values per row. */
  multi?: boolean;
};

/** One concrete index entry returned by `list_indexes`. */
export type IndexInfo = {
  /** Indexed field name. */
  field: string;
  /** Underlying index value type. */
  type: IndexType;
  /** Whether the field is indexed as multi-valued. */
  multi: boolean;
};

export type TableConfig = {
  /** Indexed fields that can be used in `get_objs(..., filter, ...)`. */
  indexes: Record<string, IndexConfig>;
  /** Event-time field used by retention and watermark logic. */
  timeField?: string;
  /** Retention window in hours for `run_retention()`. */
  retentionHours?: number;
  /** Prefix used for autogenerated distributed ids. */
  idPrefix?: string;
};

export type TableInfo = {
  /** Numeric table id allocated by the engine. */
  tableId: number;
  /** Application namespace, for example `pos`. */
  app: string;
  /** Logical database/site id, for example `miami1`. */
  db: string;
  /** Human-readable table name, for example `orders`. */
  tableName: string;
  /** Table storage mode. */
  type: TableType;
  /** Mutable table configuration. */
  config: TableConfig;
};

export type DocMeta = {
  /** Last write time known by the local engine. */
  updatedAtMs: number;
  /** Opaque content fingerprint for the current stored value. */
  etag: string;
  /** Tombstone marker for deleted rows. */
  deleted?: boolean;
};

export type ObjRow = {
  /** Object id. */
  id: string;
  /** Stored JSON payload when present. */
  value?: unknown;
  /** Metadata for present rows. */
  meta?: DocMeta;
  /** Miss reason when the requested object is absent. */
  miss?: 'NOT_FOUND' | 'PRUNED';
};

export type GetResult = {
  /** Rows returned for this page. */
  items: ObjRow[];
  /** Cursor-like offset to pass into the next `get_objs` call. */
  next_pos: number;
  /** Current retention watermark when available. */
  watermark?: Watermark | null;
};

export type ChangeEvent = {
  /** Wall-clock time when the local engine emitted the event. */
  ts: number;
  /** Event kind derived from the write operation. */
  op: 'added' | 'updated' | 'deleted';
  /** Changed object id. */
  id: string;
  /** New value for add/update events. */
  value?: unknown;
};

/** Function returned by `subscribe_objs`; call it to stop receiving events. */
export type Unsub = () => void;

export type Watermark = {
  /** Lowest still-valid event time retained by this table. */
  localMinTimeMs?: number;
};

export type BlobRecord = {
  /** Blob id. */
  id: string;
  /** Raw blob bytes. */
  bytes: Uint8Array;
  /** MIME type stored with the blob. */
  contentType: string;
  /** SHA-256 of `bytes`. */
  sha256: string;
  /** Blob size in bytes. */
  size: number;
};

export type Op = {
  /** Target table id. */
  tableId: number;
  /** Monotonic per-table sequence number. */
  op_seq: number;
  /** Operation timestamp in milliseconds. */
  ts_ms: number;
  /** Operation kind stored in the oplog. */
  op_type:
    | 'ADD'
    | 'UPDATE'
    | 'REPLACE'
    | 'DELETE'
    | 'BLOB_ADD'
    | 'BLOB_DEL'
    | 'SCHEMA';
  /** Object or blob id referenced by the operation. */
  id: string;
  /** Operation payload; structure depends on `op_type`. */
  payload: unknown;
};

export type StengIdentityOptions = {
  /** Full cluster id; used to derive `clusterShort` when one is not provided. */
  clusterId?: string;
  /** Short cluster code embedded into autogenerated ids. */
  clusterShort?: string;
};

/** Bundle container formats supported by snapshot export/import. */
export type SnapshotFormat = 'directory' | 'tar' | 'tar.gz';

/**
 * One exact table selector used by snapshot export.
 *
 * `filter` is only applied to live JSON docs. When a filter is present,
 * tombstones are omitted because deleted rows do not participate in live
 * query evaluation.
 */
export type SnapshotTableSelector = {
  /** Application namespace to export. */
  app: string;
  /** Logical database/site id to export. */
  db: string;
  /** Table name to export. */
  tableName: string;
  /** Optional live-row filter for one table. */
  filter?: Filter | null;
  /** Override blob inclusion for this table. */
  includeBlobs?: boolean;
  /** Override tombstone inclusion for this table. */
  includeTombstones?: boolean;
};

/** Inclusive selectors that determine which tables are exported into a snapshot. */
export type SnapshotScope = {
  /** Export every table whose `app` is in this list. */
  apps?: string[];
  /** Export every table whose `db` is in this list. */
  dbs?: string[];
  /**
   * Export these exact tables, optionally with table-local filters.
   *
   * Explicit table selectors override the default `includeBlobs` and
   * `includeTombstones` values for the matching table.
   */
  tables?: SnapshotTableSelector[];
};

/** Concrete resolved selection stored per table inside the snapshot bundle. */
export type SnapshotTableSelection = {
  /** Filter applied to live docs, or `null` for a full-table export. */
  filter: Filter | null;
  /** Whether blob payloads were exported for this table. */
  includeBlobs: boolean;
  /** Whether tombstones were exported for this table. */
  includeTombstones: boolean;
};

/** One exported document row inside `docs.ndjson`. */
export type SnapshotDocRecord = {
  /** Internal storage id preserved across export/import. */
  id: string;
  /** Stored JSON payload, including tombstone payloads when retained. */
  value: unknown;
  /** Stored metadata restored on import. */
  meta: DocMeta;
};

/** One exported blob metadata row inside `blobs.ndjson`. */
export type SnapshotBlobRecord = {
  /** Blob id within the table. */
  id: string;
  /** MIME type stored with the blob. */
  contentType: string;
  /** SHA-256 of the raw blob bytes. */
  sha256: string;
  /** Blob size in bytes. */
  size: number;
  /** Relative bundle path to the raw blob file. */
  path: string;
};

/** Stable table description stored in `schema.json` inside a snapshot bundle. */
export type SnapshotTableSchema = {
  /** Source application namespace. */
  app: string;
  /** Source logical database/site id. */
  db: string;
  /** Source table name. */
  tableName: string;
  /**
   * Source numeric table id.
   *
   * This is informational only. Import preserves doc ids but does not preserve
   * numeric table ids because those are local backend allocations.
   */
  sourceTableId: number;
  /** Source table type. */
  type: TableType;
  /** Source table config restored on import. */
  config: TableConfig;
  /** Watermark captured at export time. */
  watermark: Watermark | null;
  /** Effective export selection used for this table. */
  selection: SnapshotTableSelection;
};

/** One table entry inside the top-level snapshot manifest. */
export type SnapshotTableManifest = SnapshotTableSchema & {
  /** Relative file paths for this table inside the bundle. */
  files: {
    /** Relative path to `schema.json`. */
    schema: string;
    /** Relative path to `docs.ndjson`. */
    docs: string;
    /** Relative path to `blobs.ndjson` when blobs are included. */
    blobs?: string;
  };
  /** Export counts for quick inspection without opening per-table files. */
  counts: {
    /** Number of live docs exported for the table. */
    docs: number;
    /** Number of tombstones exported for the table. */
    tombstones: number;
    /** Number of blob metadata rows exported for the table. */
    blobs: number;
    /** Total blob bytes exported for the table. */
    blobBytes: number;
  };
};

/** Top-level manifest written to `manifest.json` for one logical snapshot bundle. */
export type SnapshotManifest = {
  /** Stable manifest version string. */
  formatVersion: 'steng.snapshot.v1';
  /** Wall-clock time when the snapshot export started. */
  createdAtMs: number;
  /** Backend used to create the snapshot. */
  sourceBackend: 'memory' | 'sqlite' | 'postgres';
  /** Original requested scope, or `null` when exporting all tables. */
  scope: SnapshotScope | null;
  /** Global default for blob inclusion during export. */
  includeBlobs: boolean;
  /** Global default for tombstone inclusion during export. */
  includeTombstones: boolean;
  /** All exported tables with their bundle paths and counts. */
  tables: SnapshotTableManifest[];
  /** Aggregate counts across the whole bundle. */
  totals: {
    /** Number of tables exported. */
    tables: number;
    /** Number of live docs exported. */
    docs: number;
    /** Number of tombstones exported. */
    tombstones: number;
    /** Number of blobs exported. */
    blobs: number;
    /** Total blob bytes exported. */
    blobBytes: number;
  };
};

/** Options for `export_snapshot`. */
export type ExportSnapshotOptions = {
  /**
   * Destination directory or archive path.
   *
   * If `format` is omitted, `.tar`, `.tar.gz`, and `.tgz` paths are treated as
   * archives; all other paths create directory bundles.
   */
  outputPath: string;
  /** Optional explicit bundle format override. */
  format?: SnapshotFormat;
  /** Optional table selection scope. Omit to export all tables. */
  scope?: SnapshotScope;
  /** Include blobs by default. Defaults to `true`. */
  includeBlobs?: boolean;
  /** Include tombstones by default. Defaults to `true`. */
  includeTombstones?: boolean;
};

/** Import strategy for included tables. */
export type ImportSnapshotMode = 'merge' | 'replace';

/** Conflict strategy when an imported id already exists locally. */
export type ImportSnapshotConflictMode = 'error' | 'skip' | 'replace';

/** Options for `import_snapshot`. */
export type ImportSnapshotOptions = {
  /**
   * Source directory or archive path.
   *
   * If `format` is omitted, `.tar`, `.tar.gz`, and `.tgz` paths are treated as
   * archives; all other paths are treated as extracted directory bundles.
   */
  inputPath: string;
  /** Optional explicit bundle format override. */
  format?: SnapshotFormat;
  /**
   * How to treat tables that already exist locally.
   *
   * - `merge`: keep existing table contents and apply imported rows
   * - `replace`: clear each included table before restoring the snapshot
   */
  mode?: ImportSnapshotMode;
  /**
   * What to do when an imported document/blob id already exists in merge mode.
   *
   * - `error`: fail the import
   * - `skip`: keep the local row/blob
   * - `replace`: imported state wins
   */
  conflictMode?: ImportSnapshotConflictMode;
};

/** Summary returned by `import_snapshot`. */
export type SnapshotImportResult = {
  /** Parsed manifest from the imported bundle. */
  manifest: SnapshotManifest;
  /** Number of tables touched by the import. */
  tablesImported: number;
  /** Number of tables created locally by the import. */
  createdTables: number;
  /** Number of live docs restored. */
  docsImported: number;
  /** Number of tombstones restored. */
  tombstonesImported: number;
  /** Number of blob payloads restored. */
  blobsImported: number;
  /** Number of doc/tombstone rows skipped because of conflict handling. */
  docsSkipped: number;
  /** Number of blob rows skipped because of conflict handling. */
  blobsSkipped: number;
};
