/** Supported table storage modes. */
export type TableType = "json" | "binary";

/** Secondary index types supported by `steng` filters. */
export type IndexType = "i64" | "str" | "bool" | "time" | "hash64";

/** Comparison operators accepted by `get_objs` filters. */
export type FilterOp = "==" | "!=" | ">" | ">=" | "<" | "<=" | "between" | "in" | "contains" | "prefix";

/**
 * One filter condition in `[field, operator, value]` form.
 *
 * Example: `["status", "==", "READY"]`
 */
export type FilterClause = [field: string, op: FilterOp, value: unknown];

/** A list of AND-ed filter clauses, or `null` for no filtering. */
export type Filter = FilterClause[] | null;

export type TableConfig = {
  /** Indexed fields that can be used in `get_objs(..., filter, ...)`. */
  indexes: Record<string, { type: IndexType; multi?: boolean }>;
  /** Event-time field used by retention and watermark logic. */
  timeField?: string;
  /** Retention window in hours for `run_retention()`. */
  retentionHours?: number;
  /** Prefix used for autogenerated distributed ids. */
  idPrefix?: string;
};

export type TableInfo = {
  /** Numeric table id allocated by the engine. */
  tableId: number;
  /** Application namespace, for example `pos`. */
  app: string;
  /** Logical database/site id, for example `miami1`. */
  db: string;
  /** Human-readable table name, for example `orders`. */
  tableName: string;
  /** Table storage mode. */
  type: TableType;
  /** Mutable table configuration. */
  config: TableConfig;
};

export type DocMeta = {
  /** Last write time known by the local engine. */
  updatedAtMs: number;
  /** Opaque content fingerprint for the current stored value. */
  etag: string;
  /** Tombstone marker for deleted rows. */
  deleted?: boolean;
};

export type ObjRow = {
  /** Object id. */
  id: string;
  /** Stored JSON payload when present. */
  value?: unknown;
  /** Metadata for present rows. */
  meta?: DocMeta;
  /** Miss reason when the requested object is absent. */
  miss?: "NOT_FOUND" | "PRUNED";
};

export type GetResult = {
  /** Rows returned for this page. */
  items: ObjRow[];
  /** Cursor-like offset to pass into the next `get_objs` call. */
  next_pos: number;
  /** Current retention watermark when available. */
  watermark?: Watermark | null;
};

export type ChangeEvent = {
  /** Wall-clock time when the local engine emitted the event. */
  ts: number;
  /** Event kind derived from the write operation. */
  op: "added" | "updated" | "deleted";
  /** Changed object id. */
  id: string;
  /** New value for add/update events. */
  value?: unknown;
};

/** Function returned by `subscribe_objs`; call it to stop receiving events. */
export type Unsub = () => void;

export type Watermark = {
  /** Lowest still-valid event time retained by this table. */
  localMinTimeMs?: number;
};

export type BlobRecord = {
  /** Blob id. */
  id: string;
  /** Raw blob bytes. */
  bytes: Uint8Array;
  /** MIME type stored with the blob. */
  contentType: string;
  /** SHA-256 of `bytes`. */
  sha256: string;
  /** Blob size in bytes. */
  size: number;
};

export type Op = {
  /** Target table id. */
  tableId: number;
  /** Monotonic per-table sequence number. */
  op_seq: number;
  /** Operation timestamp in milliseconds. */
  ts_ms: number;
  /** Operation kind stored in the oplog. */
  op_type: "ADD" | "UPDATE" | "REPLACE" | "DELETE" | "BLOB_ADD" | "BLOB_DEL" | "SCHEMA";
  /** Object or blob id referenced by the operation. */
  id: string;
  /** Operation payload; structure depends on `op_type`. */
  payload: unknown;
};

export type StengIdentityOptions = {
  /** Full cluster id; used to derive `clusterShort` when one is not provided. */
  clusterId?: string;
  /** Short cluster code embedded into autogenerated ids. */
  clusterShort?: string;
};
